/** Canonical trades for directory, onboarding, and contractor profile editing */
export const CONTRACTOR_TRADES = [
  "Aerial & Satellite",
  "Air Conditioning & Refrigeration",
  "Appliance Repair",
  "Architects & Design",
  "Asbestos Removal",
  "Bathroom Fitting",
  "Bricklaying",
  "Carpentry",
  "Carpet & Upholstery Cleaning",
  "Ceilings & Partitioning",
  "Chimney & Fireplace",
  "Cleaning Services",
  "Concrete & Screeding",
  "Conservatories",
  "Damp Proofing",
  "Decorating",
  "Demolition",
  "Drainage",
  "Driveways & Patios",
  "Electrical",
  "EV Charger Installation",
  "Extensions & Conversions",
  "Fencing & Gates",
  "Fire Protection",
  "Flooring",
  "Gas & Heating",
  "General Building",
  "Glazing & Double Glazing",
  "Groundwork",
  "Guttering & Fascias",
  "Handyman",
  "Insulation",
  "Interior Design",
  "Joinery",
  "Kitchen Fitting",
  "Landscaping",
  "Locksmiths",
  "Loft Conversions",
  "Painting & Decorating",
  "Pest Control",
  "Plant Hire & Operation",
  "Plastering",
  "Plumbing",
  "Pond & Water Features",
  "Removals",
  "Renewable Energy & Solar",
  "Roofing",
  "Scaffolding",
  "Security Systems",
  "Skip Hire",
  "Smart Home & AV",
  "Stonework & Masonry",
  "Structural Engineers",
  "Surveying",
  "Swimming Pools",
  "Tiling",
  "Tree Surgery",
  "Underpinning",
  "Welding & Fabrication",
  "Windows & Doors",
  "Wood Burning Stoves",
] as const;

export type ContractorTrade = (typeof CONTRACTOR_TRADES)[number];

export const TRADE_TYPES: readonly string[] = [...CONTRACTOR_TRADES];
