const LEGACY_TRADE_TYPES = [
  "Agricultural Technician",
  "Air-craft Engineer",
  "Automation Technician",
  "Auto Mechanic",
  "Boilermaker",
  "Bricklayer / Mason",
  "Carpentry",
  "Carpenter",
  "Carpet Installer",
  "Concrete Finisher",
  "Construction Inspector",
  "Construction Manager",
  "Consultant",
  "Crane Operator",
  "Drywall Installer / Finisher",
  "Electrician",
  "Energy Efficiency Consultant",
  "Elevator Mechanic",
  "Electrical",
  "Farmer",
  "Flooring",
  "Flooring Installer",
  "Gardener",
  "Gas & Heating",
  "General Building",
  "Glazing",
  "Glazier",
  "Heavy Equipment Operator",
  "HVAC Technician",
  "HVAC Technician (Heating, Ventilation, and Air Conditioning)",
  "Heating",
  "Insulation",
  "Insulation Worker",
  "Ironworker",
  "Landscaper",
  "Landscaping",
  "Machinist",
  "Mechanical Installer",
  "Painter and Decorator",
  "Painting",
  "Painting & Decorating",
  "Plasterer",
  "Plastering",
  "Plumber",
  "Plumbing",
  "Rigger",
  "Roofer",
  "Roofing",
  "Scaffolder",
  "Security System Installer",
  "Sheet Metal Worker",
  "Smart Home Technician",
  "Solar Panel Installer",
  "Tiler",
  "Tiling",
  "Tree Surgeon / Arborist",
  "Welder",
  "Wind Turbine Technician",
] as const;

const EXPANDED_TRADE_TYPES = [
  "Bricklayer",
  "Stonemason",
  "Dryliner",
  "Renderer",
  "Tiler (floor & wall)",
  "Flooring fitter",
  "Carpenter & Joiner",
  "Cabinet maker",
  "Insulation installer",
  "Demolition operative",
  "Groundworker",
  "Piledriver",
  "Steelfixer",
  "Concrete finisher",
  "Solar PV installer",
  "EV charger installer",
  "Lift/elevator engineer",
  "Fire alarm engineer",
  "Security systems installer",
  "CCTV installer",
  "Data/network cabling engineer",
  "Home automation installer",
  "Gas engineer",
  "Boiler installer",
  "Heating engineer",
  "Underfloor heating installer",
  "Renewable energy installer (heat pumps, biomass)",
  "Refrigeration & air conditioning (HVAC)",
  "Sprinkler system installer",
  "Kitchen fitter",
  "Bathroom fitter",
  "Window & door fitter (UPVC/timber/aluminium)",
  "Stairlift installer",
  "Loft conversion specialist",
  "Conservatory fitter",
  "Garage door installer",
  "Blinds & curtain fitter",
  "Painter & decorator",
  "Wallpaper hanger",
  "Muralist",
  "Signwriter",
  "Graining & marbling specialist",
  "Polished concrete/microcement finisher",
  "Venetian plaster specialist",
  "Landscape gardener",
  "Hard landscaper (patios, driveways, walls)",
  "Arborist/tree surgeon",
  "Fencer",
  "Decking installer",
  "Pond & water feature specialist",
  "Irrigation installer",
  "Turf layer",
  "Domestic cleaner",
  "Commercial/office cleaner",
  "End-of-tenancy cleaner",
  "Carpet & upholstery cleaner",
  "Pressure washer/jet washer",
  "Window cleaner",
  "Gutter cleaner",
  "Chimney sweep",
  "Oven cleaner",
  "Graffiti removal specialist",
  "Drain cleaner/jetter",
  "Pest controller",
  "Mould remediation specialist",
  "Car mechanic (petrol/diesel)",
  "EV mechanic",
  "MOT tester",
  "Panel beater/body repair",
  "Vehicle painter/sprayer",
  "Wheel alignment/tracking specialist",
  "Tyre fitter",
  "Windscreen fitter",
  "Auto electrician",
  "Car detailer/valeter",
  "HGV/lorry mechanic",
  "Motorcycle mechanic",
  "Mobile mechanic",
  "Handyman",
  "Property maintenance operative",
  "Locksmith",
  "Safe engineer",
  "Damp proofer",
  "Damp Proofing",
  "Waterproofer",
  "Structural repair specialist",
  "Underpinning specialist",
  "Asbestos removal operative",
  "Surveyor (building/structural)",
  "Audio-visual installer",
  "Home cinema fitter",
  "Satellite/aerial installer",
  "Smart home/IoT installer",
  "IT support & network engineer",
  "Metal fabricator",
  "Blacksmith",
  "Ironmonger",
  "Sheet metal worker",
  "Pipefitter",
  "Powder coater",
  "Marine engineer",
  "Boat builder/repairer",
  "Industrial maintenance engineer",
  "Factory machinery fitter",
  "Crane operator",
  "Forklift engineer",
  "Plant mechanic (excavators, diggers)",
  "Forensic cleaner/crime scene cleaner",
  "Swimming pool installer & maintenance",
  "Gym equipment installer",
  "Monument & headstone engraver",
  "Clock & watch repairer",
  "Musical instrument repairer",
  "Taxidermist",
  "Farrier",
  "Saddler",
  "Funeral director",
] as const;

export const TRADE_TYPES = Array.from(
  new Set<string>([...LEGACY_TRADE_TYPES, ...EXPANDED_TRADE_TYPES]),
);

export const DEFAULT_TRADE_FILTERS = [
  "General Building",
  "Electrical",
  "Plumbing",
  "Carpentry",
  "Painting",
  "Roofing",
] as const;
