// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnvxfzmdjpsswjszwbvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudnhmem1kanBzc3dqc3p3YnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzI3NjYsImV4cCI6MjA3MzQ0ODc2Nn0.rzTUVRPxybLJZ9asE04lOg-5pjFp6FZXWT3JzvshI8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});